version: '3.7'
services:
  mysql-user:
    image: mysql:latest
    container_name: mysql-user
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user
    volumes:
      - ./mysql-user-data:/var/lib/mysql
  mysql-game:
    image: mysql:latest
    container_name: mysql-game
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=game
    volumes:
      - ./mysql-game-data:/var/lib/mysql

  redis-user:
    image: redis:latest
    container_name: redis-user
    ports:
      - "6379:6379"
    volumes:
      - ./redis-user-data:/data
  redis-game:
    image: redis:latest
    container_name: redis-game
    ports:
      - "6380:6379"
    volumes:
      - ./redis-user-data:/data

  etcd:
    image: quay.io/coreos/etcd:v3.5.0-arm64

    container_name: etcd
    command: >
      etcd
      --name etcd-node
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"