github:
  client_id: 66eec55XXXXXX687db1b
  client_secrets: a31f7c17XXXXXXXXXXf442ead9320f538e7dbbb
aliyun:
  access_key_id: LTAI5tEeNXXXXXXXXq1ntNttn
  access_key_secret: semg0r9AdFXuVXXXXXXXXZMLZp5

